# -  /SLGxBOT/

FROM quay.io/SLGxBOT/Poorna-MD-v2
RUN git clone https://github.com/SLGxBOT/Poorna-Md /root/Poorna
WORKDIR /root/Poorna/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SLGxBOT/ Don't change this name,

